baseURL = "https://securisotto.vah.wtf"
theme = "risotto"
title = "Security Day 2026"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"
buildFuture = true

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

[menu]
  [[menu.main]]
    name = "timeline"
    url = "/timeline/"
    weight = 1

  [[menu.main]]
    name = "pixelwars"
    url = "/pixelwars/"
    weight = 2

  [[menu.main]]
    name = "faq"
    url = "/faq/"
    weight = 3

  [[menu.main]]
    name = "notice"
    url = "/notice/"
    weight = 4

[markup.goldmark.renderer]
unsafe = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
