baseURL = "https://security-day.hs-offenburg.de"
theme = "risotto"
title = "Security Day 2026"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "gruvbox-dark"

[menu]
  [[menu.main]]
    identifier = "overview"
    name = "overview"
    url = "/overview/"
    weight = 1

  [[menu.main]]
    identifier = "pixels"
    name = "pixels"
    url = "/pixels/"
    weight = 2

  [[menu.main]]
    identifier = "notice"
    name = "notice"
    url = "/notice/"
    weight = 3

[markup.goldmark.renderer]
unsafe = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
